'use server';
/**
 * @fileOverview Generates a video validation task based on user's assessment answers.
 *
 * - generateVideoTask - A function that generates video validation tasks.
 * - GenerateVideoTaskInput - The input type for the generateVideoTask function.
 * - GenerateVideoTaskOutput - The return type for the generateVideoTask function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateVideoTaskInputSchema = z.object({
  answers: z.record(z.string(), z.string()).describe('A record of the user answers, where the key is the competency and the value is the answer.'),
});
export type GenerateVideoTaskInput = z.infer<typeof GenerateVideoTaskInputSchema>;

const VideoTaskSchema = z.object({
  competency: z.string().describe('The competency the task is related to.'),
  task: z.string().describe('The detailed instruction for the user. It should ask them to elaborate on their original answer, provide concrete examples, and details to verify their experience.'),
});

const GenerateVideoTaskOutputSchema = z.array(VideoTaskSchema).describe('An array of 3 randomly selected video tasks.');
export type GenerateVideoTaskOutput = z.infer<typeof GenerateVideoTaskOutputSchema>;

export async function generateVideoTask(input: GenerateVideoTaskInput): Promise<GenerateVideoTaskOutput> {
  return generateVideoTaskFlow(input);
}

const generateVideoTaskPrompt = ai.definePrompt({
  name: 'generateVideoTaskPrompt',
  input: {schema: GenerateVideoTaskInputSchema},
  output: {schema: GenerateVideoTaskOutputSchema},
  prompt: `You are an expert in creating validation tasks for job candidates. Your goal is to verify if the candidate's answers are based on real experience and not fabricated or generated by another AI.

From the list of competencies and answers provided, randomly select exactly 3.

For each of the 3 selected competencies, create a detailed instruction for the user to record a video. The instruction must be specific and based on the user's original answer.

The instruction for each task must:
1.  Reference a specific part of their original answer for that competency.
2.  Ask them to elaborate on it with more depth, specific details, and real-life examples.
3.  Request concrete examples, metrics, outcomes, or situations that only someone with real experience would know. For example, ask about the specific challenges faced, the people involved, or the measurable results of their actions.
4.  The tone should be professional and encouraging, clearly explaining that the goal is to validate their expertise.

The final output must be a valid JSON array containing exactly 3 objects, where each object has a "competency" and a "task" key.

User's Answers:
{{#each answers}}
- Competency: {{@key}}
- Answer: {{{this}}}
{{/each}}
`,
});


const generateVideoTaskFlow = ai.defineFlow(
  {
    name: 'generateVideoTaskFlow',
    inputSchema: GenerateVideoTaskInputSchema,
    outputSchema: GenerateVideoTaskOutputSchema,
  },
  async input => {
    const {output} = await generateVideoTaskPrompt(input);
    return output!;
  }
);
